$applicationlist =@("*KACE*")
$results = @()
$reglocations = @("HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall","HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall")

foreach($location in $reglocations)
    {
        foreach($application in $applicationlist)
        {
            $results += (Get-ChildItem -Path $location | Get-ItemProperty | Where-Object {$_.DisplayName -like $application} | Select-Object -Property DisplayName, PSChildName, Version)
        }
    }
    
foreach($UnInstall in $results)
    {
                
        $MSIArguments = @(
        '/x'
        $UnInstall.PSChildName
        '/qn'    
        '/L*v "C:\Windows\Temp\' + $($UnInstall.DisplayName)+'.log"'
        'REBOOT=REALLYSUPPRESS'
        )
               
        $Uninstaller = Start-Process "msiexec.exe" -ArgumentList $MSIArguments -Wait -NoNewWindow -ErrorAction Stop -PassThru
                    
    }
# SIG # Begin signature block
# MIIPkQYJKoZIhvcNAQcCoIIPgjCCD34CAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUxda5VA0qaFu4yJchrnMDQocV
# vMmgggzUMIIGTTCCBDWgAwIBAgITTAAAAF5sLsHUJfebVgAAAAAAXjANBgkqhkiG
# 9w0BAQsFADBuMRMwEQYKCZImiZPyLGQBGRYDZWR1MRMwEQYKCZImiZPyLGQBGRYD
# d3d1MRMwEQYKCZImiZPyLGQBGRYDZGlyMRQwEgYKCZImiZPyLGQBGRYEdW5pdjEX
# MBUGA1UEAxMOV1dVIElzc3VpbmcgQ0EwHhcNMTgwODE0MjAzMDU2WhcNMjEwODEz
# MjAzMDU2WjB6MRMwEQYKCZImiZPyLGQBGRYDZWR1MRMwEQYKCZImiZPyLGQBGRYD
# d3d1MRMwEQYKCZImiZPyLGQBGRYDZGlyMRQwEgYKCZImiZPyLGQBGRYEdW5pdjES
# MBAGA1UECxMJRW1wbG95ZWVzMQ8wDQYDVQQDEwZmYXZyb2UwggEiMA0GCSqGSIb3
# DQEBAQUAA4IBDwAwggEKAoIBAQDbFmoCa4LjtHjbTpdwKVv4iWuN3Ccka1PLXv3a
# wZAbBNWWeuti+U3DFHoUV1DutNvboBBvnPRISVk8FWUunIVprqrNq+v580T+4M/B
# BOVZ4yz91628C3gyF3McG5NccfUIToVQvbuKzPhCuepD2v1qfehxRTqv7CaCAtJa
# 4fvaa66V9VONHBov4zT2JdYxeRz6nIifIAc0i8LJA16vUVk0QskmHd23OSalI8cW
# KuWxbp2LwdZWcYxfjhlaTIdFAKWLI6cbJTJn/50UJ0tpg+g6et3eyW3lCYOa8ODo
# jO2iYRxxPjWTf6tcYSFVgBHPRk1fWuLamOuQyEgiPbWwLyJ5AgMBAAGjggHWMIIB
# 0jA9BgkrBgEEAYI3FQcEMDAuBiYrBgEEAYI3FQiGueFvh4iRe4X9kwiB6Zc2hLj/
# ZTiF9qg9hMPcbAIBZAIBBDATBgNVHSUEDDAKBggrBgEFBQcDAzALBgNVHQ8EBAMC
# B4AwGwYJKwYBBAGCNxUKBA4wDDAKBggrBgEFBQcDAzAdBgNVHQ4EFgQUQ6oJIiSQ
# KYWyhwJdNlCppD9HZmgwHwYDVR0jBBgwFoAUVpGAicahm/FaZGWxHmtvH592IVQw
# ZwYDVR0fBGAwXjBcoFqgWIYqaHR0cDovL3BraTEud3d1LmVkdS9XV1UlMjBJc3N1
# aW5nJTIwQ0EuY3JshipodHRwOi8vcGtpMi53d3UuZWR1L1dXVSUyMElzc3Vpbmcl
# MjBDQS5jcmwwfgYIKwYBBQUHAQEEcjBwMDYGCCsGAQUFBzAChipodHRwOi8vcGtp
# MS53d3UuZWR1L1dXVSUyMElzc3VpbmclMjBDQS5jcnQwNgYIKwYBBQUHMAKGKmh0
# dHA6Ly9wa2kyLnd3dS5lZHUvV1dVJTIwSXNzdWluZyUyMENBLmNydDApBgNVHREE
# IjAgoB4GCisGAQQBgjcUAgOgEAwOZmF2cm9lQHd3dS5lZHUwDQYJKoZIhvcNAQEL
# BQADggIBADG/8HLdu81G1vf3uYrhkbx75xBv2GkrWCzBpHUxTOJnH/xbndzugUkE
# KC3YLBiSPst4X8PMdcstpirBqwRMm13jUseuXcwaUaYLhiRGd15DY2w85lEEpLcg
# z2A9bVxmpKcZx2GJDGLQuVS2TIcPj3pxMLwnAe5HOR5TjMyo8Zpg9D4JCK1DP3+f
# FkMuQuPDamjXtw/6Cu9Cdj/A6KEMt4btiMUCJCfII7dPx3575xy036cooJlEswgy
# 27r+3oNi7ipqygMQ3WqR+f4cVWNhu4Iq3lPaX+TjpgRydGkmecJUWWmGu5mde9uW
# VCluK3cUpMz32o4S+o2MoiiYHsvezCmJinPiYP0p6w5/n8cGx+fUVcrlWIbGz4GA
# 6f4jeRWUSGgqRbuGQ0bQ1r7AlWErqgnm8DM6FFqxyTqplPQCXOCgLO7/6QFLC/S2
# sb3EWeDL/m0p9aBt7GKAuW7/5OnNYZfhMNkXra3Y7b9XLor51J0MhFnBOJL4YADs
# LwGgLk7LDO7rXYukkB6yQ73osGYfISDBBIriF5zCXnBGM5g4/3IdofxyVHEj06sv
# 9OHBoEGxcW0vXwHeMvrhXPKgR8sNsur+qR7bfs5gnJyM3e24EgDTMyv4Ua0CH5Ck
# 0DGxOfQ302ujgczqUOLdsQjVrCIGLaxVk3WVJBs9EcNYlOcWhieYMIIGfzCCBGeg
# AwIBAgITeQAAAAL772FfZLeYjwAAAAAAAjANBgkqhkiG9w0BAQsFADAWMRQwEgYD
# VQQDEwtXV1UgUm9vdCBDQTAeFw0xNzAzMTUyMzQxMDVaFw0yNzAzMTUyMzUxMDVa
# MG4xEzARBgoJkiaJk/IsZAEZFgNlZHUxEzARBgoJkiaJk/IsZAEZFgN3d3UxEzAR
# BgoJkiaJk/IsZAEZFgNkaXIxFDASBgoJkiaJk/IsZAEZFgR1bml2MRcwFQYDVQQD
# Ew5XV1UgSXNzdWluZyBDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
# AKuVzs3EvMDSjoPasTtzVlHuNqyPAmCHBws8SZUk7k1FL7kP0JtYQIRQRfXa1IUY
# E0rhwam5vIiUFfUBxsOazEcZ0LyE+DqZmRsjHQV3t6wtOsNcxV0vyRIhl0/QYa19
# MvpMmpBo4/uOEUTtYMv7fw9MzDWcQDmBDR9+CSV63cVpfhnWTEDeMVJHtaY8zX8O
# kIQ76AYRjgib2gnW0VhDq6IrXOrGtwr399VOykTu4P5XkubJXuXhntacJr6O/KN9
# NPEl6AGgMQ+HdK3TOUEOa2wK+GRJvhnqYzSZMcqlzCQxZixmbI3tbTB1cTztlUnI
# m6gMAHvwzCf0VmL9dRRZ4YmpYMqRjWVbrc9uxC9K6BLVud4Shqr88t7HZyjNp9s8
# LpyEBoozHA1Fdabzq3VlNMXKNmJkzhOnnC4X4CnHMZNzrHblQwVO8U2U86OlgB1k
# kP2asIaXnW8207H/wfwpRr+X9MPSUYPfBP5/McZXtFm77i3Gfif5cf4GXfexTneQ
# f6hv3f20Yh8rBwyT3CbRD7ZylleOtLY6RaQYAjFFtPwq3PmBnBWZn33ekSHR9sWO
# Nk8zCVceO07OBOQS2mgjC6TjPs9dvU8sXeATYtEvIYz7YG47QOAgSE64jJMnEXiJ
# WuyUFahjsAZs844F+V7AaDppUYS6b8/gZNepd4Kyl1gzAgMBAAGjggFsMIIBaDAQ
# BgkrBgEEAYI3FQEEAwIBADAdBgNVHQ4EFgQUVpGAicahm/FaZGWxHmtvH592IVQw
# GQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB
# /wQFMAMBAf8wHwYDVR0jBBgwFoAUm4dc03Z5vIm9giw0eIdeY6ialC8wYQYDVR0f
# BFowWDBWoFSgUoYnaHR0cDovL3BraTEud3d1LmVkdS9XV1UlMjBSb290JTIwQ0Eu
# Y3JshidodHRwOi8vcGtpMi53d3UuZWR1L1dXVSUyMFJvb3QlMjBDQS5jcmwweAYI
# KwYBBQUHAQEEbDBqMDMGCCsGAQUFBzAChidodHRwOi8vcGtpMS53d3UuZWR1L1dX
# VSUyMFJvb3QlMjBDQS5jcnQwMwYIKwYBBQUHMAKGJ2h0dHA6Ly9wa2kyLnd3dS5l
# ZHUvV1dVJTIwUm9vdCUyMENBLmNydDANBgkqhkiG9w0BAQsFAAOCAgEAHuIvjjkL
# DGnhTjTOKwJ+STEumBxiabcwe1MGfrXOaQ5K2LJ9hc8m95M+QasbhDsTQhAxYQa3
# tq57eY8ylQtgd9OnR2+E0LAt1xkzeZJjqG5VT+ZZnCaM8yo7LBEUpgtpm4TQngZh
# I93bSBUVGhrvblerblUoUDxKMXgQNEBhZY/LP1wweIXWk9YVvgVR2Ijo41ffhO3o
# IjFsk73ZReukdM5jpnAFZ2KRmJ/uCR05Dng99hHmrzOsgx/S0mhp/MfCsW16N1CB
# 0kU4rRF+tE63iYw4IwB7EroCKwLyIlnA/NcZXzfcjwlv95tFKlV4uxVUZbc6Q+ql
# +uPoYUw5x1k1l9MHQGzwYU6isTjw9swgeOTDAKZISiLRqahmP59aejiEoKXGhJVC
# JHAwIEaN2iFsaCzL+63vS01C4Q2173e28rVd7CLeGQi4vhMfYfthIL44QuKYOdRy
# fH4yQvB4NHv+ikSo5hRJ1S+FqLNKmrf6YwirHzvfGKpM+825Jg3QhWhrU+GsAdX+
# OEsgkvMIvBMWPJhROrduiw9H/JZ9rSt65PkA0gUtKFfyt6CJxXm4YooK5mcjqJPO
# bdjHF15EGHTFaiTKVgQkFRoYmHfY/l54fqDQDgWJq63LMc0aV3Wclg1iQrPQa2nW
# kqnkN/ePeXEJjBju4zM/GOLfZSYTMz0xo+MxggInMIICIwIBATCBhTBuMRMwEQYK
# CZImiZPyLGQBGRYDZWR1MRMwEQYKCZImiZPyLGQBGRYDd3d1MRMwEQYKCZImiZPy
# LGQBGRYDZGlyMRQwEgYKCZImiZPyLGQBGRYEdW5pdjEXMBUGA1UEAxMOV1dVIElz
# c3VpbmcgQ0ECE0wAAABebC7B1CX3m1YAAAAAAF4wCQYFKw4DAhoFAKB4MBgGCisG
# AQQBgjcCAQwxCjAIoAKAAKECgAAwGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQw
# HAYKKwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUwIwYJKoZIhvcNAQkEMRYEFIdL
# DG+f10dRLKyzsOEfdmXcpvu8MA0GCSqGSIb3DQEBAQUABIIBAAJQlTSGRDkLLz1X
# dv5DIgZgwd0r4e5nPEJSK87IXgq6WYD1QFuop6dbNdzLG0r8vdFicygBPzD/oKKL
# jHaun3LMBYD8TZ/mnGgXhEhhgxw/fchHuGlreaN7QRc93CPZcX0PX1NDnzh7xCWx
# ag16GoY95pJTpwow7znwkN6vyLicuZQG4hji+RpTXKFWz6f426ZTdKxBabHPgcng
# HPMoPdPwYP7EGKYGKnfDQqr9XjYR1AQjiMXKRWVjpm46uWqVy5AFqcHmo1+JuSNU
# PAvrJlI0AZf/6XzIuw/cbTZdrIIkY8UmZUqWhDqtbp95uvERWAOYKwfjZ3yFuA7R
# QD2PcG4=
# SIG # End signature block
